### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by StephanHoyer**

### CODE REVIEW

**Comment by StephanHoyer** [comment]
I really recommend using [greenkeeper](http://greenkeeper.io/) to keep dependencies up to date

**Comment by overlookmotel** [comment]
Hi @StephanHoyer.

Thanks for the PR. Actually I'm hoping to remove the bluebird dependency in next release in favour of native JS Promise (and publish a new module `co-series-bluebird` for those who prefer bluebird).

In the meantime, to use `bluebird` v3 with `co-series`, you can do this:

``` js
var Bluebird3 = require('bluebird');
var series = require('co-series').use(Bluebird3);
```

**Comment by StephanHoyer** [comment]
Even better!

**Comment by overlookmotel** [comment]
Hi @StephanHoyer.

FYI, v3.0.0 (just published) removes the dependency on bluebird and uses native JS promises instead.

I've published a separate module [co-series-bluebird](https://www.npmjs.org/packages/co-series-bluebird) for people who prefer bluebird (including me), and it's using bluebird v3.

**Pull request closed without merging**
